daysUntilStale: 7
daysUntilClose: 7

staleLabel: stale

markComment: >
  This issue has been automatically marked stale after 7 days of Inactivity.
  It will be closed if no further activity occurs. 
closeComment: false
